# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '博客类别', 'verbose_name_plural': '博客类别'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '博客标签', 'verbose_name_plural': '博客标签'},
        ),
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=0, verbose_name='分类数目'),
        ),
        migrations.AddField(
            model_name='tag',
            name='number',
            field=models.IntegerField(default=0, verbose_name='标签数目'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Category', verbose_name='博客类别'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='myblog.Tag', verbose_name='博客标签'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='博客类别'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='博客标签'),
        ),
    ]
